from datetime import datetime


def generate_report(analysis: str, log_input: str,
                    issue_type: str, sources: list) -> str:
    """
    Wrap the AI analysis in a structured incident report
    with metadata and source references.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    source_lines = ""
    if sources:
        source_lines = "\n## Knowledge Sources Used\n"
        for i, src in enumerate(sources, 1):
            source_lines += f"{i}. [{src['category']}] {src['source']} (score: {src['score']})\n"

    report = f"""# Incident Report
Generated: {timestamp}
Issue Category: {issue_type}

## Original Input
{log_input[:300]}{'...' if len(log_input) > 300 else ''}

{analysis}
{source_lines}
---
*Generated by AI DevOps Assistant — Phase 4 Multi-Agent System*
"""
    return report